Name:		ros-groovy-smd-wifi-monitor
Version:	0.0.2
Release:	0%{?dist}
Summary:	ROS smd_wifi_monitor package

Group:		Development/Tools
License:	BSD
Source0:	%{name}-%{version}.tar.gz

BuildRequires:	ros-groovy-catkin,ros-groovy-roscpp,ros-groovy-pluginlib,ros-groovy-std-msgs,ros-groovy-diagnostic-updater,ros-groovy-message-generation,libnl3-devel,ros-groovy-nodelet
Requires:	ros-groovy-pluginlib,ros-groovy-roscpp,ros-groovy-gencpp,ros-groovy-message-runtime,ros-groovy-std-msgs,ros-groovy-diagnostic-updater,libnl3,ros-groovy-nodelet

%description
ROS device monitor for nl80211-compatible wireless NICs


%prep
%setup -q


%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/groovy/setup.sh" ]; then . "/opt/ros/groovy/setup.sh"; fi
mkdir build && cd build
cmake .. \
	-DCMAKE_VERBOSE_MAKEFILE=ON \
	-DCATKIN_BUILD_BINARY_PACKAGE="1" \
	-DCMAKE_INSTALL_PREFIX="/opt/ros/groovy" \
	-DCMAKE_PREFIX_PATH="/opt/ros/groovy" \
	-DSETUPTOOLS_DEB_LAYOUT=OFF
make %{?_smp_mflags}


%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/groovy/setup.sh" ]; then . "/opt/ros/groovy/setup.sh"; fi
cd build
make install DESTDIR=%{buildroot}


%files
%doc
/opt/ros/groovy


%changelog
* Wed Apr 10 2013 Scott K Logan <logans@cottsay.net> - 0.0.2-0
- autogenerated

